language: cpp
git:
- submodules: false
before_install:
- sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- mkdir build
- cd build
- cmake ..
- cmake --build .
- cmake --build . --target ip_filter_tst
- cmake --build . --target package
deploy:
    provider: script
    skip_cleanup: true
    script:
    - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -utantskii:$BINTRAY_API_KEY "https://api.bintray.com/content/myorguniqueid/otus/ip_filter/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

